### ISSUE TITLE
gulp: SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by pettersh** [Puzzlepart/prosjektportalen#120]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Environment
[ ] SharePoint Online
[ ] SharePoint 2013

#### Summary

1. I just cloned the latest from master
2. npm install
3. gulp bombs with the following error:

```
C:\dev-git\prosjektportalen\.tasks\@configuration.js:1
(function (exports, require, module, __filename, __dirname) { let autoprefixer = require('autoprefixer-stylus'),
                                                              ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at C:\dev-git\prosjektportalen\gulpfile.js:9:35
    at Array.forEach (native)
    at C:\dev-git\prosjektportalen\gulpfile.js:8:26
```

I'm running on Windows 10, npm 4.2.0, gulp 3.9.1

#### Version

Please specify what version ou are using: [ ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
_If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!_

#### Observed Behavior
_If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section._

#### Steps to Reproduce
_If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section._

**Comment by olemp** [comment]
This might be relevant: https://markgoodyear.com/2015/06/using-es6-with-gulp/

**Comment by olemp** [comment]
What does `gulp -v` yield for you @pettersh?

**Comment by olemp** [comment]
@pettersh I've added `'use strict'` and renamed `gulpfile.js` to `gulpfile.babel.js`.

**Comment by pettersh** [comment]
@olemp gulp -v => 3.9.1 for both CLI and local version

I pulled down lates from dev, and got the changes using babel, but I still get the same error I had 2 days ago.

I get the same error running in PowerShell windows and in vscode

`Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\dev-git\prosjektportalen> gulp -v
[12:15:39] Requiring external module babel-register
[12:15:39] CLI version 3.9.1
[12:15:39] Local version 3.9.1
PS C:\dev-git\prosjektportalen> npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
PS C:\dev-git\prosjektportalen> gulp
[12:16:26] Requiring external module babel-register
C:\dev-git\prosjektportalen\webpack.config.development.js:6
module.exports = (devtool = "source-map") => {
                          ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at loader (C:\dev-git\prosjektportalen\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\dev-git\prosjektportalen\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:/dev-git/prosjektportalen/.tasks/package.js:4:24)
    at Module._compile (module.js:409:26)`

**Comment by tarjeieo** [comment]
I've never seen this error. I'm currently running with npm 5.0.3, gulp 3.9.1 and typescript 2.3.4.

Curious about why you get this!

**Comment by pettersh** [comment]
I just cloned the dev branch to a customer laptop (Win 7) and got the samme error there:
`C:\Users\a926353\prosjektportalen\webpack.config.development.js:6
module.exports = (devtool = "source-map") => {
                          ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at loader (C:\Users\a926353\prosjektportalen\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\a926353\prosjektportalen\node_modules\babel-reg
ister\lib\node.js:154:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:/Users/a926353/prosjektportalen/.tasks/package.js:4:24)
    at Module._compile (module.js:409:26)
 PS C:\Users\a926353\prosjektportalen> node -v
v4.4.7
PS C:\Users\a926353\prosjektportalen> npm -v
5.0.3
PS C:\Users\a926353\prosjektportalen> gulp -v
[10:53:36] Requiring external module babel-register
[10:53:36] CLI version 3.9.1
[10:53:36] Local version 3.9.1`

**Comment by olemp** [comment]
I removed the ES6 default thing. Try again now @pettersh

**Comment by pettersh** [comment]
@olemp 
`PS C:\Users\a926353\prosjektportalen> git pull
remote: Counting objects: 40, done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 40 (delta 28), reused 38 (delta 26), pack-reused 0
Unpacking objects: 100% (40/40), done.
From https://github.com/Puzzlepart/prosjektportalen
   d1c5baa..ca6b0fa  dev        -> origin/dev
Updating d1c5baa..ca6b0fa
Fast-forward
 .tasks/package.js                                  |  2 +-
 html2canvas                                        |  1 +
 src/js/Util/index.ts                               |  9 +++++
 src/js/WebParts/ProjectInfo/IProjectInfoProps.ts   | 10 +++++
 .../WebParts/ProjectStatus/RiskOverview/index.tsx  | 46 +++++++++++++++-------
 .../WebParts/ProjectStatus/SectionHeader/index.tsx |  3 +-
 templates/root/en-US.resx                          |  6 ++-
 templates/root/no-NB.resx                          |  3 ++
 webpack.config.development.js                      |  2 +-
 9 files changed, 63 insertions(+), 19 deletions(-)
 create mode 160000 html2canvas
PS C:\Users\a926353\prosjektportalen> npm install
removed 7 packages in 6.722s
PS C:\Users\a926353\prosjektportalen> gulp
[11:59:37] Requiring external module babel-register
C:\Users\a926353\prosjektportalen\webpack.config.development.js:14
    let rules = [{
    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at loader (C:\Users\a926353\prosjektportalen\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\a926353\prosjektportalen\node_modules\babel-reg
ister\lib\node.js:154:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:/Users/a926353/prosjektportalen/.tasks/package.js:4:24)
    at Module._compile (module.js:409:26)
 PS C:\Users\a926353\prosjektportalen>`

**Comment by pettersh** [comment]
@olemp It's another error now. I assume replacing 'let' with 'var' will resolve this

**Comment by olemp** [comment]
@pettersh That will probably give another error related to arrow functions. This makes no sense.

**Comment by olemp** [comment]
@okms Does this work for you?

**Comment by okms** [comment]
I'm not near a computer, but i promise i'll test when i get back home later today

**Comment by pettersh** [comment]
@olemp I don't dissagree. We just need to figure out why this fails in some environments and some not. If there are anything we can add to the https://github.com/Puzzlepart/prosjektportalen/wiki/Development page to have all environments setup equally, it would be great

**Comment by olemp** [comment]
Did it work when installing gulp globally?

**Comment by olemp** [comment]
@okms Did you test?

**Comment by okms** [comment]
```PS C:\code\prosjektportalen> gulp
[16:21:12] Requiring external module babel-register
[16:21:15] Using gulpfile C:\code\prosjektportalen\gulpfile.babel.js
[16:21:15] Starting 'default'...
[16:21:15] Starting 'clean'...
[16:21:15] Starting 'clean:lib'...
[16:21:15] Finished 'clean:lib' after 132 ms
[16:21:15] Starting 'clean:dist'...
[16:21:15] Finished 'clean:dist' after 12 ms
[16:21:15] Starting 'clean:templates_temp'...
[16:21:15] Finished 'clean:templates_temp' after 43 ms
[16:21:15] Finished 'clean' after 195 ms
[16:21:15] Starting 'build:jsonresources'...
[16:21:15] Finished 'build:jsonresources' after 48 ms
[16:21:15] Starting 'lint:ts'...
Warning: The 'no-use-before-declare' rule requires type checking
[16:21:17] Finished 'lint:ts' after 1.69 s
[16:21:17] Starting 'copy:assets:dist'...
[16:21:17] Starting 'build:lib'...
[16:21:17] Starting 'build:theme'...
[16:21:17] Finished 'build:theme' after 89 ms
[16:21:17] Starting 'package:styles'...
[16:21:18] Finished 'package:styles' after 1.25 s
[16:21:18] Finished 'copy:assets:dist' after 1.36 s
[gulp-typescript] 2322 Type '{ Folder: string; Src: string; Url: string; Overwrite: true; WebParts: { Title: string; Zone: str...' is not assignable to type 'IFile'.
  Types of property 'WebParts' are incompatible.
    Type '{ Title: string; Zone: string; Order: number; PropertyOverrides: { name: string; type: string; va...' is not assignable to type 'IWebPart[]'.
      Type '{ Title: string; Zone: string; Order: number; PropertyOverrides: { name: string; type: string; va...' is not assignable to type 'IWebPart'.
        Object literal may only specify known properties, and 'PropertyOverrides' does not exist in type 'IWebPart'.
> file: src\js\Provision\Template\Objects\Files\Assigned.ts:
> [12]             PropertyOverrides: [{
> [13]                 name: "Title",
> [14]                 type: "string",
> [15]                 value: __("WebPart_MyTasks_Title"),
> [16]             },
> [17]             {
> [18]                 name: "ListUrl",
> [19]                 type: "string",
> [20]                 value: `{site}/${__("Lists_Tasks_Url")}`,
> [21]             },
> [22]             {
> [23]                 name: "TitleUrl",
> [24]                 type: "string",
> [25]                 value: `{site}/${__("DefaultView_Tasks_Url")}`,
> [26]             }],
[gulp-typescript] 2322 Type '{ Folder: string; Src: string; Url: string; Overwrite: true; WebParts: { Title: string; Zone: str...' is not assignable to type 'IFile'.
  Types of property 'WebParts' are incompatible.
    Type '{ Title: string; Zone: string; Order: number; PropertyOverrides: { name: string; type: string; va...' is not assignable to type 'IWebPart[]'.
      Type '{ Title: string; Zone: string; Order: number; PropertyOverrides: { name: string; type: string; va...' is not assignable to type 'IWebPart'.
        Object literal may only specify known properties, and 'PropertyOverrides' does not exist in type 'IWebPart'.
> file: src\js\Provision\Template\Objects\Files\MoM.ts:
> [12]             PropertyOverrides: [{
> [13]                 name: "Title",
> [14]                 type: "string",
> [15]                 value: __("WebPart_LatestsTasks_Title"),
> [16]             },
> [17]             {
> [18]                 name: "ListUrl",
> [19]                 type: "string",
> [20]                 value: `{site}/${__("Lists_Tasks_Url")}`,
> [21]             },
> [22]             {
> [23]                 name: "TitleUrl",
> [24]                 type: "string",
> [25]                 value: `{site}/${__("DefaultView_Tasks_Url")}`,
> [26]             }],
[gulp-typescript] 2322 Type '{ Folder: string; Src: string; Url: string; Overwrite: true; WebParts: ({ Title: string; Zone: st...' is not assignable to type 'IFile'.
  Types of property 'WebParts' are incompatible.
    Type '({ Title: string; Zone: string; Order: number; PropertyOverrides: { name: string; type: string; v...' is not assignable to type 'IWebPart[]'.
      Type '{ Title: string; Zone: string; Order: number; PropertyOverrides: { name: string; type: string; va...' is not assignable to type 'IWebPart'.
        Type '{ Title: string; Zone: string; Order: number; PropertyOverrides: { name: string; type: string; va...' is not assignable to type 'IWebPart'.
          Object literal may only specify known properties, and 'PropertyOverrides' does not exist in type 'IWebPart'.
> file: src\js\Provision\Template\Objects\Files\Nofilter.ts:
> [12]             PropertyOverrides: [{
> [13]                 name: "Title",
> [14]                 type: "string",
> [15]                 value: __("WebPart_Tasks_Title"),
> [16]             },
> [17]             {
> [18]                 name: "ListUrl",
> [19]                 type: "string",
> [20]                 value: `{site}/${__("Lists_Tasks_Url")}`,
> [21]             },
> [22]             {
> [23]                 name: "TitleUrl",
> [24]                 type: "string",
> [25]                 value: `{site}/${__("DefaultView_Tasks_Url")}`,
> [26]             }],
[gulp-typescript] 2322 Type '{ Folder: string; Src: string; Url: string; Overwrite: true; Properties: { Title: string; Content...' is not assignable to type 'IFile'.
  Types of property 'WebParts' are incompatible.
    Type '({ Title: string; Zone: string; Order: number; Contents: { FileSrc: string; }; } | { Title: strin...' is not assignable to type 'IWebPart[]'.
      Type '{ Title: string; Zone: string; Order: number; Contents: { FileSrc: string; }; } | { Title: string...' is not assignable to type 'IWebPart'.
        Type '{ Title: string; Zone: string; Order: number; Contents: { FileSrc: string; }; }' is not assignable to type 'IWebPart'.
          Types of property 'Contents' are incompatible.
            Type '{ FileSrc: string; }' is not assignable to type 'IWebPartContents'.
              Object literal may only specify known properties, and 'FileSrc' does not exist in type 'IWebPartContents'.
> file: src\js\Provision\Template\Objects\Files\ProjectHome.ts:
> [18]                 FileSrc: "{wpgallery}/ProjectPhases.webpart",
[16:21:24] TypeScript: 4 semantic errors
[16:21:24] TypeScript: 7 declaration errors
[16:21:24] TypeScript: emit succeeded (with errors)
[16:21:24] Finished 'build:lib' after 7.29 s
[16:21:24] Starting 'package:code'...
Hash: 7fdf7a534b3b8a84922b
Version: webpack 2.6.1
Time: 17189ms
         Asset     Size  Chunks                    Chunk Names
    pp.main.js  5.22 MB       0  [emitted]  [big]  main
pp.main.js.map  6.57 MB       0  [emitted]         main
chunk    {0} pp.main.js, pp.main.js.map (main) 5.15 MB [entry] [rendered]
    [8] ./~/sp-pnp-js/lib/pnp.js 2.03 kB {0} [built]
   [29] (webpack)/buildin/global.js 509 bytes {0} [built]
  [260] ./lib/js/Util/StampVersion.js 2.93 kB {0} [built]
  [413] ./lib/js/index.js 902 bytes {0} [built]
  [414] ./~/babel-polyfill/lib/index.js 833 bytes {0} [built]
  [415] ./~/whatwg-fetch/fetch.js 12.7 kB {0} [built]
  [456] ./lib/js/Forms/index.js 3.12 kB {0} [built]
  [549] ./lib/js/WebParts/index.js 2.18 kB {0} [built]
  [553] ./~/core-js/fn/regexp/escape.js 107 bytes {0} [built]
  [726] ./~/core-js/modules/es7.string.trim-right.js 215 bytes {0} [built]
  [727] ./~/core-js/modules/es7.symbol.async-iterator.js 42 bytes {0} [built]
  [728] ./~/core-js/modules/es7.symbol.observable.js 39 bytes {0} [built]
  [733] ./~/core-js/shim.js 7.38 kB {0} [built]
 [1067] ./~/regenerator-runtime/runtime.js 24.4 kB {0} [built]
 [1116] multi babel-polyfill whatwg-fetch ./lib/js/index.js 52 bytes {0} [built]
     + 1102 hidden modules
[16:21:42] Finished 'package:code' after 18 s
[16:21:42] Starting 'package'...
[16:21:42] Finished 'package' after 4.02 μs
[16:21:42] Starting 'build:pnp'...
[16:21:42] Starting 'copy:pnp'...
[16:21:42] Finished 'copy:pnp' after 273 ms
[16:21:42] Starting 'copy:dist'...
[16:21:42] Finished 'copy:dist' after 72 ms
[16:21:42] Starting 'stamp:version::templates'...
[16:21:42] Finished 'stamp:version::templates' after 146 ms
[16:21:43] Finished 'build:pnp' after 1.48 s
[16:21:43] Finished 'default' after 28 s
PS C:\code\prosjektportalen>

```

info about my tool chain

```
PS C:\code\prosjektportalen> gulp -v
[16:23:19] Requiring external module babel-register
[16:23:19] CLI version 3.9.1
[16:23:19] Local version 3.9.1
PS C:\code\prosjektportalen> npm -v
5.0.3
PS C:\code\prosjektportalen> git status -v
On branch dev
Your branch is up-to-date with 'origin/dev'.
nothing to commit, working directory clean
PS C:\code\prosjektportalen> git reflog
3e7c263 HEAD@{0}: pull: Fast-forward
c6036ae HEAD@{1}: checkout: moving from master to dev
ef2e2b3 HEAD@{2}: pull: Fast-forward
5d39841 HEAD@{3}: commit: #117 retaining hyphens in processed url string
cc53f54 HEAD@{4}: checkout: moving from dev to master
c6036ae HEAD@{5}: checkout: moving from master to dev
cc53f54 HEAD@{6}: pull: Fast-forward
699b0a8 HEAD@{7}: commit: Removing all non-letter or number chars, trunkating string at 80 (#117)
e58cc19 HEAD@{8}: pull: Fast-forward
0ef18aa HEAD@{9}: clone: from https://github.com/Puzzlepart/prosjektportalen.git
PS C:\code\prosjektportalen>```

**Comment by okms** [comment]
So as far as i can tell things are building for me without the error specified in this ticket. Im building from powershell. I do get some nasty TS errors though.

**Comment by olemp** [comment]
Can not reproduce. Must be an evironment issue.

**Comment by olemp** [comment]
Can not reproduce. Must be an evironment issue.
