### ISSUE TITLE
Update documentation. Error: Cannot find module './@settings.js'

### ISSUE THREAD

**Issue by pettersh** [Puzzlepart/prosjektportalen#184]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[x] Bug

[ ] Question

#### Environment

[ ] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Summary

If following build instructions on https://github.com/Puzzlepart/prosjektportalen/wiki/Development, you get the following error if you haven't created a local @settings.js file.

Add this step to build instructions

`PS C:\dev-git\prosjektportalen> gulp
[13:21:15] Requiring external module babel-register
module.js:471
    throw err;
    ^

Error: Cannot find module './@settings.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:/dev-git/prosjektportalen/.tasks/watch.js:10:16)
    at Module._compile (module.js:570:32)
    at loader (C:\dev-git\prosjektportalen\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\dev-git\prosjektportalen\node_modules\babel-register\lib\node.js:154
:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at C:/dev-git/prosjektportalen/gulpfile.babel.js:9:35
    at Array.forEach (native)
    at load.forEach.path (C:/dev-git/prosjektportalen/gulpfile.babel.js:8:26)
    at Array.forEach (native)
    at Object.<anonymous> (C:/dev-git/prosjektportalen/gulpfile.babel.js:7:6)
    at Module._compile (module.js:570:32)
    at loader (C:\dev-git\prosjektportalen\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\dev-git\prosjektportalen\node_modules\babel-register\lib\node.js:154
:7)
    at Module.load (module.js:487:32)`

#### Version

Please specify what version you are using: [ ]

You can find the version you are using in the bottom left corner of any page in the Project portal site.

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
_If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!_

#### Observed Behavior
_If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section._

#### Steps to Reproduce
_If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section._

**Comment by olemp** [comment]
Documentation updated
https://github.com/Puzzlepart/prosjektportalen/wiki/Development

You need to create your own `settings.js` in the folder `.tasks`. Use the `settings.sample.js` as a base.
